backlog_capacity = 1000

[profile_config]
flag_prof_start = 0
enable = false
flag_prof_duration = 0

[http_config]
allow_origin = "*"
timeout = 3
enable = true
listen_port = "1337"
listen_ip = "0.0.0.0"

[ws_config]
panic_on_internal = true
in_buffer_capacity = 2048
panic_on_queue = false
panic_on_protocol = false
method_strict = false
panic_on_capacity = false
key_strict = false
max_connections = 800
listen_port = "4337"
shutdown_on_interrupt = true
out_buffer_grow = true
panic_on_io = false
out_buffer_capacity = 2048
encrypt_server = false
fragments_grow = true
panic_on_timeout = false
enable = true
queue_size = 200
thread_number = 2
masking_strict = false
listen_ip = "0.0.0.0"
fragment_size = 65535
fragments_capacity = 100
tcp_nodelay = false
panic_on_shutdown = false
panic_on_new_connection = false
in_buffer_grow = true
panic_on_encoding = false

[new_tx_flow_config]
buffer_duration = 30000000
count_per_batch = 30
