[package]
name = "jsonrpc_types"
version = "0.1.0"
authors = ["root"]

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

uuid = { version = "0.5", features = ["v4"] }

libproto = { path = "../libproto" }